# Generated by Django 4.1.2 on 2022-11-01 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_id', models.CharField(blank=True, max_length=128, null=True)),
                ('source_name', models.CharField(blank=True, max_length=128, null=True)),
                ('author_name', models.CharField(blank=True, max_length=128, null=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('url', models.CharField(max_length=255)),
                ('image_url', models.TextField(blank=True, null=True)),
                ('published_at', models.DateTimeField()),
                ('content', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'news',
                'verbose_name_plural': 'news',
                'db_table': 'news',
                'ordering': ['-published_at'],
                'unique_together': {('source_name', 'author_name', 'title', 'published_at')},
            },
        ),
    ]
